CHANGELOG.md
rustfst-python-bench/rustfst_python_bench/algorithms/connect.py
rustfst/src/algorithms/connect.rs
rustfst/src/algorithms/minimize.rs
rustfst/src/algorithms/reverse.rs
rustfst/src/algorithms/shortest_path.rs
rustfst/src/fst_impls/vector/vector_fst.rs

- Change implementation of `connect` algorithm which is now on par with OpenFST's one. Also works now for big fsts, no longer crashes.

Optimize connect algorithm

---

.gitignore
CHANGELOG.md
rustfst/src/lib.rs

Make KDELTA const public outside the crate

---

CHANGELOG.md
README.md
rustfst-tests-data/main.cpp
rustfst/src/algorithms/mod.rs
rustfst/src/algorithms/replace.rs
rustfst/src/fst_traits/allocable_fst.rs
rustfst/src/lib.rs
rustfst/src/tests_openfst/algorithms/determinize.rs
rustfst/src/tests_openfst/algorithms/minimize.rs
rustfst/src/tests_openfst/algorithms/mod.rs
rustfst/src/tests_openfst/algorithms/replace.rs
rustfst/src/tests_openfst/algorithms/reverse.rs
rustfst/src/tests_openfst/fst_impls/const_fst.rs
rustfst/src/tests_openfst/mod.rs

ReplaceFst

---

CHANGELOG.md
rustfst/src/symbol_table.rs

Fix : https://github.com/Garvys/rustfst/issues/56

Use BufWriter to serialize SymbolTable

---

CHANGELOG.md
rustfst/src/algorithms/isomorphic.rs
rustfst/src/fst_traits/mutable_fst.rs

- Added `emplace_arc` and `emplace_arc_unchecked` as provided methods to the `MutableFst` trait.

EmplaceArc

---

rustfst/src/algorithms/arc_filters.rs
rustfst/src/algorithms/arc_unique.rs
rustfst/src/algorithms/closure.rs
rustfst/src/algorithms/concat.rs
rustfst/src/algorithms/determinize.rs
rustfst/src/algorithms/factor_weight.rs
rustfst/src/algorithms/fst_convert.rs
rustfst/src/algorithms/minimize.rs
rustfst/src/algorithms/mod.rs
rustfst/src/algorithms/push.rs
rustfst/src/algorithms/queue.rs
rustfst/src/algorithms/replace.rs
rustfst/src/algorithms/rm_epsilon.rs
rustfst/src/algorithms/shortest_distance.rs
rustfst/src/algorithms/union.rs
rustfst/src/fst_traits/serializable_fst.rs
rustfst/src/lib.rs
rustfst/src/tests_openfst/algorithms/factor_weight_gallic.rs
rustfst/src/tests_openfst/algorithms/factor_weight_identity.rs
rustfst/src/tests_openfst/algorithms/replace.rs

- Remove `BorrowFst` trait
- Add documentation

Documentation

---

rustfst/src/algorithms/cache/cache_impl.rs
rustfst/src/algorithms/cache/cache_state.rs
rustfst/src/algorithms/cache/fst_impl.rs
rustfst/src/algorithms/cache/vector_cache_state.rs
rustfst/src/algorithms/factor_weight.rs
rustfst/src/algorithms/replace.rs
rustfst/src/arc.rs
rustfst/src/fst_impls/const_fst/data_structure.rs
rustfst/src/fst_impls/const_fst/iterators.rs
rustfst/src/fst_impls/vector_fst/data_structure.rs
rustfst/src/fst_traits/final_states_iterator.rs
rustfst/src/tests_openfst/algorithms/dynamic_fst.rs

Relax contraints semiring

---

.travis.yml
CHANGELOG.md
rustfst/src/algorithms/add_super_final_state.rs
rustfst/src/algorithms/arc_map.rs
rustfst/src/fst_impls/vector_fst/mutable_fst.rs
rustfst/src/fst_traits/mutable_fst.rs

- Add `take_final_weight` and `take_final_weight_unchecked` to MutableFst API.

Take final weight

---

CHANGELOG.md
rustfst/src/algorithms/dynamic_fst.rs
rustfst/src/algorithms/factor_weight.rs
rustfst/src/algorithms/fst_convert.rs
rustfst/src/algorithms/mod.rs
rustfst/src/algorithms/push.rs
rustfst/src/algorithms/replace.rs
rustfst/src/algorithms/rm_epsilon.rs
rustfst/src/fst_impls/const_fst/iterators.rs
rustfst/src/fst_impls/vector_fst/iterators.rs
rustfst/src/fst_traits/iterators.rs
rustfst/src/fst_traits/mod.rs
rustfst/src/tests_openfst/algorithms/dynamic_fst.rs
rustfst/src/tests_openfst/algorithms/fst_convert.rs
rustfst/src/tests_openfst/algorithms/mod.rs
rustfst/src/tests_openfst/fst_impls/const_fst.rs
rustfst/src/tests_openfst/fst_impls/test_fst_into_iterator.rs
rustfst/src/tests_openfst/io/const_fst_text_serialization.rs
rustfst/src/tests_openfst/mod.rs

Fst convert consuming its input

---

CHANGELOG.md
rustfst/src/algorithms/closure.rs
rustfst/src/algorithms/concat.rs
rustfst/src/algorithms/dynamic_fst.rs
rustfst/src/algorithms/union.rs
rustfst/src/fst_impls/const_fst/fst.rs
rustfst/src/fst_impls/vector_fst/fst.rs
rustfst/src/fst_impls/vector_fst/mutable_fst.rs
rustfst/src/fst_traits/fst.rs
rustfst/src/fst_traits/mutable_fst.rs
rustfst/src/tests_openfst/fst_impls/const_fst.rs
rustfst/src/tests_openfst/io/vector_fst_bin_deserializer.rs

Allow to modify SymbolTables attached to a ConstFst

---

CHANGELOG.md
rustfst/src/algorithms/arc_map.rs
rustfst/src/algorithms/arc_mappers/identity_arc_mapper.rs
rustfst/src/algorithms/arc_mappers/input_epsilon_mapper.rs
rustfst/src/algorithms/arc_mappers/invert_weight_mapper.rs
rustfst/src/algorithms/arc_mappers/output_epsilon_mapper.rs
rustfst/src/algorithms/arc_mappers/plus_mapper.rs
rustfst/src/algorithms/arc_mappers/quantize_mapper.rs
rustfst/src/algorithms/arc_mappers/rm_weight_mapper.rs
rustfst/src/algorithms/arc_mappers/times_mapper.rs
rustfst/src/algorithms/encode.rs
rustfst/src/algorithms/queues/auto_queue.rs
rustfst/src/algorithms/queues/top_order_queue.rs

Immutable Arc Mapper

---

CHANGELOG.md
rustfst/src/fst_traits/iterators.rs
rustfst/src/semirings/semiring.rs
rustfst/src/semirings/union_weight.rs

- Semiring impls are required to be 'static

Static semiring

---

CHANGELOG.md
build_bench.sh
openfst_benchmark/bench_compose.cpp
openfst_benchmark/bench_compose_lookahead.cpp
openfst_benchmark/utils.h
rustfst-cli/src/binary_fst_algorithm.rs
rustfst-cli/src/cmds/compose.rs
rustfst-cli/src/cmds/mod.rs
rustfst-cli/src/main.rs
rustfst-python-bench/rustfst_python_bench/algorithms/compose.py
rustfst-python-bench/rustfst_python_bench/algorithms/supported_algorithms.py
rustfst-python-bench/rustfst_python_bench/bench_composition.py
rustfst/src/algorithms/compose/lookahead_matchers/label_lookahead_matcher.rs

Add scripts to benchmark the composition algorithm

Benchmark scripts for composition

---

CHANGELOG.md
openfst_benchmark/bench_compose.cpp
rustfst/src/algorithms/closure/closure_fst.rs
rustfst/src/algorithms/compose/compose.rs
rustfst/src/algorithms/compose/compose_fst.rs
rustfst/src/algorithms/compose/compose_fst_op.rs
rustfst/src/algorithms/concat/concat_fst.rs
rustfst/src/algorithms/determinize/determinize_fsa.rs
rustfst/src/algorithms/determinize/determinize_static.rs
rustfst/src/algorithms/factor_weight/factor_weight.rs
rustfst/src/algorithms/factor_weight/factor_weight_fst.rs
rustfst/src/algorithms/lazy_fst_revamp/lazy_fst.rs
rustfst/src/algorithms/lazy_fst_revamp/state_table.rs
rustfst/src/algorithms/replace/replace.rs
rustfst/src/algorithms/replace/replace_fst.rs
rustfst/src/algorithms/union/union_fst.rs

Bench composition without lookahead
- Rustfst master : 14.53 s
- This branch : 6.77 s
- Openfst : 4.46 s

Speed-up composition

---

CHANGELOG.md
rustfst/src/algorithms/compose/compose_fst.rs
rustfst/src/algorithms/lazy_fst_revamp/fst_cache.rs

- Remove trait bound on Default in FstCache trait

Remove trait bound on Default in FstCache trait

---

CHANGELOG.md
rustfst/src/algorithms/compose/compose_fst.rs
rustfst/src/algorithms/lazy_fst_revamp/first_cache.rs
rustfst/src/algorithms/lazy_fst_revamp/mod.rs
rustfst/src/algorithms/lazy_fst_revamp/simple_vec_cache.rs

Composition time on my benchmark went from 6.88s to 5.27s. OpenFst is at 4.55s

Add SimpleVecCache and use it by default in composition

---

CHANGELOG.md
rustfst/src/algorithms/determinize/determinize_fsa_op.rs
rustfst/src/tests_openfst/mod.rs

Fixed bug in `Determinize`: `HashMap` -> `BTreeMap` for `LabelMap`.

Fix determinize

---

CHANGELOG.md
rustfst/src/algorithms/lazy/cache/cache_status.rs
rustfst/src/algorithms/lazy/cache/first_cache.rs
rustfst/src/algorithms/lazy/cache/fst_cache.rs
rustfst/src/algorithms/lazy/cache/simple_hash_map_cache.rs
rustfst/src/algorithms/lazy/cache/simple_vec_cache.rs

- add `num_known_traits` to `FstCache` trait

FST Cache API extension

---

rustfst/src/algorithms/minimize.rs
rustfst/src/symbol_table.rs
rustfst/src/tests_openfst/utils.rs
rustfst/src/utils/labels_to_fst.rs

This fixes #158 plus a few clippy warnings. I wish I could say it was elegant, but it works, does away with needless clones and minimizes allocation churn.

Fix minimize implementation

---

.ci/native.sh
.github/workflows/linux.yml
.github/workflows/native.yml
.gitignore
rustfst-python/rustfst/fst.py
rustfst-python/setup.py

- Add mac ci
- Rename python package to rustfst-python

Add mac ci

---

rustfst-python/rustfst/algorithms/replace.py
rustfst-python/rustfst/algorithms/tr_unique.py
rustfst-python/rustfst/algorithms/union.py
rustfst-python/setup.py
scripts/release.sh

An issue in the path of the README file to read prevent Pypi from displaying a Project Description. This PR fixes it.

Fix long description in setup.py

---

rustfst-ffi/src/fst/vector_fst.rs
rustfst-python/rustfst/fst/vector_fst.py
rustfst-python/tests/test_fst.py

Fix : https://github.com/Garvys/rustfst/issues/188

Add `to_bytes` and `from_bytes` for `VectorFst` in the Python binding

---

rustfst-ffi/src/algorithms/compose.rs
rustfst-python/rustfst/algorithms/compose.py
rustfst-python/tests/algorithms/test_compose.py
rustfst/src/algorithms/compose/compose_static.rs
rustfst/src/algorithms/compose/matchers/mod.rs
rustfst/src/algorithms/compose/matchers/sigma_matcher.rs
rustfst/src/algorithms/compose/mod.rs
rustfst/src/fst_traits/macros.rs
rustfst/src/fst_traits/serializable_fst.rs

- Allow support of Sigma Transitions when composing two FSTs
- Use the SymbolTable when displaying an Fst which has attached SymbolTables.

Sigma transitions

---

.github/workflows/native.yml
Cargo.lock
rustfst-cli/Cargo.toml
rustfst-cli/src/binary_fst_algorithm.rs
rustfst-cli/src/cmds/project.rs
rustfst-cli/src/main.rs
rustfst-cli/src/unary_fst_algorithm.rs
rustfst/src/algorithms/compose/compose_fst_op.rs
rustfst/src/algorithms/compose/interval_set.rs
rustfst/src/algorithms/determinize/mod.rs
rustfst/src/algorithms/encode/mod.rs
rustfst/src/algorithms/factor_weight/mod.rs
rustfst/src/algorithms/lazy/cache/mod.rs
rustfst/src/algorithms/partition.rs
rustfst/src/algorithms/replace/replace_fst_op.rs
rustfst/src/algorithms/rm_epsilon/mod.rs
rustfst/src/algorithms/shortest_path.rs
rustfst/src/fst_impls/vector_fst/mutable_fst.rs
rustfst/src/semirings/semiring.rs

The bump of clap is necessary in order to remove a vulnerability.
One consequence of that is that rust version now needs to be >= 1.74.0

Bump clap to 4

---

Cargo.lock
rustfst-cli/Cargo.toml
rustfst-ffi/Cargo.toml
rustfst-python/setup.py
rustfst/Cargo.toml

rustfst is very stable and has been used in production for years so it's time to cook the 1.0.0 🎉

Release 1.0.0

---

README.md
rustfst-ffi/Cargo.toml
rustfst-python/mkdocs.yml
rustfst-python/setup.py

Update URLs in all the documentation/config
