CHANGELOG.md, src/drawing_config.rs, src/fst_traits/expanded_fst.rs, src/fst_traits/fst.rs, src/fst_traits/macros.rs, src/lib.rs, src/semirings/semiring.rs
- Add `is_one` and `is_zero` to `Semiring` API.
- Add `is_start` to `Fst` API.
- `draw` to generate a file representing an `ExpandedFst` in dot format that can be displayed with GraphViz.
=> Implement FST drawing

CHANGELOG.md, Cargo.toml, rustfst-cli/Cargo.toml, rustfst-cli/src/connect.rs, rustfst-cli/src/main.rs, rustfst-cli/src/minimize.rs, rustfst-cli/src/pretty_errors.rs, rustfst/src/lib.rs, rustfst/src/parsers/bin_fst/vector_fst.rs
- Added the crate `rustfst-cli` as a CLI for the lib. It supports the subcommands:
- `minimize` for the minimization
- `connect` for the connect algorithm
- Added a prelude to `rustfst` to reduce the number of imports necessary when using the lib.
=> Introducing the CLI for minimize and connect + prelude

CHANGELOG.md, rustfst/src/algorithms/arc_map.rs, rustfst/src/algorithms/composition.rs, rustfst/src/algorithms/concat.rs, rustfst/src/algorithms/connect.rs, rustfst/src/algorithms/determinize.rs, rustfst/src/algorithms/factor_weight.rs, rustfst/src/algorithms/isomorphic.rs, rustfst/src/algorithms/minimize.rs, rustfst/src/algorithms/push.rs, rustfst/src/algorithms/reverse.rs, rustfst/src/algorithms/reweight.rs, rustfst/src/algorithms/rm_epsilon.rs, rustfst/src/algorithms/shortest_path.rs, rustfst/src/algorithms/state_sort.rs, rustfst/src/algorithms/union.rs, rustfst/src/algorithms/visitors/scc_visitors.rs, rustfst/src/algorithms/weight_convert.rs, rustfst/src/fst_impls/const_fst/fst.rs, rustfst/src/fst_impls/vector_fst/fst.rs, rustfst/src/fst_impls/vector_fst/mutable_fst.rs, rustfst/src/fst_impls/vector_fst/test.rs, rustfst/src/fst_properties/compute_fst_properties.rs, rustfst/src/fst_traits/final_states_iterator.rs, rustfst/src/fst_traits/fst.rs, rustfst/src/fst_traits/macros.rs, rustfst/src/fst_traits/mutable_fst.rs, rustfst/src/fst_traits/paths_iterator.rs, rustfst/src/parsers/bin_fst/vector_fst.rs
- Added `final_weight_unnchecked_mut` to `MutableFst` trait.
- `final_weight` method of `Fst` trait now returns a `Fallible`. Fail only when the state doesn't exist.
- `final_weight_mut` method of `Fst` trait now returns a `Fallible`. Fail only when the state doesn't exist.
- `FinalStateIterator` now returns reference to final weights instead of copy.
=> final_weight() now returs Fallible

CHANGELOG.md, rustfst/src/fst_traits/expanded_fst.rs
This is to make sure that the `label` in a DOT file is rendered correctly even if it consists of several words (contains spaces). The addition of quotes also prevents dot from complaining about a syntax error if no  `DrawingConfig.title` is specified (e.g. when using `DrawingConfig::default()`) which previously resulted in the line `label = ;` being added to the DOT file.
=> Add quotes around DOT file title

CHANGELOG.md, rustfst/src/algorithms/determinize.rs, rustfst/src/algorithms/fst_convert.rs, rustfst/src/algorithms/minimize.rs, rustfst/src/algorithms/push.rs, rustfst/src/algorithms/reverse.rs, rustfst/src/algorithms/weight_convert.rs, rustfst/src/fst_impls/vector_fst/allocable_fst.rs, rustfst/src/fst_impls/vector_fst/mod.rs, rustfst/src/fst_impls/vector_fst/mutable_fst.rs, rustfst/src/fst_traits/allocable_fst.rs, rustfst/src/fst_traits/mod.rs, rustfst/src/fst_traits/mutable_fst.rs, rustfst/src/tests_openfst/algorithms/determinize.rs, rustfst/src/tests_openfst/algorithms/minimize.rs, rustfst/src/tests_openfst/algorithms/reverse.rs
While running algorithms that modify an FST or build a new one, in many cases we know in advance how much we will allocate. For this purpose, we discuss with @Garvys about a dedicated trait for this end.
=> Fst Memory Management

CHANGELOG.md, rustfst/src/algorithms/cache/fst_impl.rs, rustfst/src/algorithms/cache/mod.rs, rustfst/src/algorithms/cache/state_table.rs, rustfst/src/algorithms/determinize.rs, rustfst/src/algorithms/factor_weight.rs, rustfst/src/algorithms/replace.rs
- Change internal implementation of `Replace`, `Determinize` and `FactorWeight` to share more code by creating the trait `FstImpl` and the struct `StateTable`.
=> Factorize dynamic implementations of Replace, Determinize and FactorWeight

CHANGELOG.md, rustfst-tests-data/main.cpp, rustfst/src/fst_impls/const_fst/serializable_fst.rs, rustfst/src/fst_impls/vector_fst/mutable_fst.rs, rustfst/src/fst_impls/vector_fst/serializable_fst.rs, rustfst/src/fst_traits/mutable_fst.rs, rustfst/src/parsers/bin_fst/fst_header.rs, rustfst/src/parsers/bin_symt/mod.rs, rustfst/src/parsers/bin_symt/nom_parser.rs, rustfst/src/parsers/mod.rs, rustfst/src/symbol_table.rs, rustfst/src/tests_openfst/io/vector_fst_bin_deserializer.rs, rustfst/src/tests_openfst/mod.rs, rustfst/src/tests_openfst/test_symt.rs
Fix : #58 and https://github.com/Garvys/rustfst/issues/51
- Added `write` and `read` method to the `SymbolTable` API to serialize and deserialize SymbolTable in binary format consistently with OpenFst.
- Added `unset_input_symbols` and `unset_output_symbols` methods to remove the symbol tables attached to a mutable fst.
- Fix bug when the parsing of fst in binary format crashed because a symbol table was attached to the fst. The symbol tables are now retrieved directly from the fst file.
=> Serde binary format SymbolTable

rustfst/Cargo.toml
Found with cargo udeps (https://github.com/est31/cargo-udeps)
=> Move doc-comment to dev dependencies

CHANGELOG.md, rustfst/src/algorithms/add_super_final_state.rs, rustfst/src/algorithms/arc_map.rs, rustfst/src/algorithms/mod.rs
=> Add super final state

CHANGELOG.md, rustfst/src/algorithms/push.rs, rustfst/src/algorithms/queues/auto_queue.rs, rustfst/src/algorithms/queues/top_order_queue.rs, rustfst/src/algorithms/reverse.rs, rustfst/src/algorithms/shortest_distance.rs, rustfst/src/algorithms/shortest_path.rs, rustfst/src/semirings/boolean_weight.rs, rustfst/src/semirings/gallic_weight.rs, rustfst/src/semirings/integer_weight.rs, rustfst/src/semirings/log_weight.rs, rustfst/src/semirings/mod.rs, rustfst/src/semirings/probability_weight.rs, rustfst/src/semirings/product_weight.rs, rustfst/src/semirings/semiring.rs, rustfst/src/semirings/string_weight.rs, rustfst/src/semirings/tropical_weight.rs, rustfst/src/semirings/union_weight.rs, rustfst/src/tests_openfst/test_weights.rs
Add the `ReverseBack` trait that must be implemented for `Semiring::ReverseWeight`. Allows to avoid using transmute when we have `weight.reverse().reverse()` calls.
=> Reverse back

CHANGELOG.md, rustfst/src/fst_impls/const_fst/serializable_fst.rs, rustfst/src/fst_impls/vector_fst/serializable_fst.rs, rustfst/src/parsers/bin_fst/fst_header.rs, rustfst/src/semirings/probability_weight.rs, rustfst/src/tests_openfst/io/const_fst_bin_serializer.rs, rustfst/src/tests_openfst/io/const_fst_text_serialization.rs, rustfst/src/tests_openfst/io/mod.rs, rustfst/src/tests_openfst/io/vector_fst_bin_serializer.rs, rustfst/src/tests_openfst/io/vector_fst_text_serialization.rs, rustfst/src/tests_openfst/mod.rs
=> Symbol table serialization when serializing a FST (Binary) 

CHANGELOG.md, rustfst-tests-data/main.cpp, rustfst/src/algorithms/queues/scc_queue.rs, rustfst/src/algorithms/shortest_path.rs, rustfst/src/tests_openfst/algorithms/mod.rs, rustfst/src/tests_openfst/algorithms/queue.rs, rustfst/src/tests_openfst/mod.rs
- Fix an issue in `SccQueue` which made the `is_empty()` call super slow. As a result, an important speed-up can be observed when running the `shortest_path` algorithm.
=> Speed up shortest path

CHANGELOG.md, rustfst/src/algorithms/compose/label_reachable.rs
Remove call to `collect_vec` when calling `LabelReachable.reach()`.
=> Speed-up label reachable

CHANGELOG.md, rustfst/src/fst_impls/const_fst/mod.rs, rustfst/src/fst_impls/const_fst/serializable_fst.rs, rustfst/src/fst_impls/vector_fst/mod.rs, rustfst/src/fst_impls/vector_fst/parse_const.rs, rustfst/src/fst_impls/vector_fst/serializable_fst.rs, rustfst/src/tests_openfst/io/const_fst_bin_deserializer.rs, rustfst/src/tests_openfst/mod.rs
- Add method `read_from_const` to `VectorFst` allowing to load a `VectorFst` from a `ConstFst` file.
=> Read VectorFst from ConstFst file

CHANGELOG.md, rustfst/src/algorithms/compose/compose_fst.rs, rustfst/src/algorithms/determinize/determinize_fsa.rs, rustfst/src/algorithms/factor_weight/factor_weight_fst.rs, rustfst/src/algorithms/lazy_fst_revamp/fst_cache.rs, rustfst/src/algorithms/lazy_fst_revamp/lazy_fst.rs, rustfst/src/algorithms/lazy_fst_revamp/lazy_fst_2.rs, rustfst/src/algorithms/lazy_fst_revamp/simple_hash_map_cache.rs, rustfst/src/algorithms/replace/replace_fst.rs, rustfst/src/algorithms/rm_epsilon/rm_epsilon_fst.rs, rustfst/src/fst_impls/const_fst/fst.rs, rustfst/src/fst_impls/vector_fst/fst.rs, rustfst/src/fst_traits/fst.rs
- `num_trs` and `num_trs_unchecked` are now mandatory methods of the `Fst` trait. This allows removing useless calls to `Arc::clone`.
=> Speed up num_trs()

CHANGELOG.md, rustfst/src/lib.rs
Make `rustiest::prelude` as the main entry point for mostly used structs, traits, etc.
=> Extend prelude re-export

CHANGELOG.md, rustfst/src/algorithms/compose/compose_filters/mod.rs, rustfst/src/algorithms/compose/compose_fst.rs, rustfst/src/algorithms/compose/label_reachable.rs, rustfst/src/algorithms/compose/lookahead_filters/lookahead_compose_filter.rs, rustfst/src/algorithms/compose/lookahead_matchers/label_lookahead_matcher.rs, rustfst/src/algorithms/compose/lookahead_matchers/mod.rs, rustfst/src/algorithms/compose/lookahead_matchers/tr_lookahead_matcher.rs, rustfst/src/algorithms/compose/lookahead_matchers/trivial_lookahead_matcher.rs, rustfst/src/algorithms/compose/matchers/mod.rs, rustfst/src/algorithms/compose/matchers/sorted_matcher.rs
- The `Matcher` object now has a trait bound on an `Fst` instead of on an `ExpandedFst` allowing composing lazy fsts.
=> Allow Composition of Lazy Fsts

CHANGELOG.md, rustfst/src/algorithms/compose/compose_fst.rs, rustfst/src/tests_openfst/algorithms/compose.rs
- Make `ComposeFst` clonable if all the elements that compose it are clonable.
=> ComposeFst clonable if possible

CHANGELOG.md, rustfst/src/algorithms/lazy/mod.rs, rustfst/src/algorithms/lazy/state_table.rs, rustfst/src/fst_impls/const_fst/serializable_fst.rs, rustfst/src/fst_impls/vector_fst/parse_const.rs, rustfst/src/fst_impls/vector_fst/serializable_fst.rs, rustfst/src/parsers/bin_fst/fst_header.rs, rustfst/src/parsers/bin_fst/utils_parsing.rs, rustfst/src/parsers/bin_symt/nom_parser.rs, rustfst/src/parsers/nom_utils.rs, rustfst/src/semirings/gallic_weight.rs, rustfst/src/semirings/log_weight.rs, rustfst/src/semirings/probability_weight.rs, rustfst/src/semirings/product_weight.rs, rustfst/src/semirings/semiring.rs, rustfst/src/semirings/string_weight.rs, rustfst/src/semirings/tropical_weight.rs, rustfst/src/semirings/union_weight.rs, rustfst/src/symbol_table.rs
- Added a `BuildHasher` generic parameter to `SymbolTable` as well as a method `with_hasher`.
- Change internal implementation of `SymbolTable`: now used a Vec and a `HashMap` instead of two `HashMap`s. As a result, doesn't support `SymbolTable` with hole anymore.
=> SymbolTable improvements

rustfst/src/fst_impls/const_fst/serializable_fst.rs, rustfst/src/fst_impls/vector_fst/serializable_fst.rs, rustfst/src/fst_traits/serializable_fst.rs
I found that there was a bit of duplication in the `SerializableFst` trait impls, also offering a broader interface (reading from `&[u8]` and writing into an arbitrary `Write` will likely make it easier to integrate RustFst with other systems, and also allow us to test without a filesystem (not included in this PR).
=> factor out fs ops in read/write

rustfst/src/parsers/text_symt/nom_parser.rs
In order to be compliant with OpenFST symbol table text format, it is required to support single space character as a separator when parsing a textual symbol table.
See [here](https://github.com/mjansche/openfst/blob/5be570c4e84a5eae1325d8c6c43fdbba3683863e/src/lib/symbol-table.cc#L31):
```
DEFINE_string(fst_field_separator, "\t ", "Set of characters used as a separator between printed fields");
```
=> Fix text symbol table parsing

.github/workflows/native.yml, rustfst-ffi/src/algorithms/mod.rs, rustfst-ffi/src/algorithms/randgen.rs, rustfst-python/rustfst/algorithms/randgen.py, rustfst-python/rustfst/fst/vector_fst.py, rustfst-python/tests/algorithms/test_randgen.py, rustfst/Cargo.toml, rustfst/src/algorithms/connect.rs, rustfst/src/algorithms/mod.rs, rustfst/src/algorithms/randgen/mod.rs, rustfst/src/algorithms/randgen/rand_state.rs, rustfst/src/algorithms/randgen/randgen_config.rs, rustfst/src/algorithms/randgen/randgen_fst.rs, rustfst/src/algorithms/randgen/randgen_fst_op.rs, rustfst/src/algorithms/randgen/randgen_visitor.rs, rustfst/src/algorithms/randgen/tr_sampler.rs, rustfst/src/algorithms/randgen/tr_selector.rs, rustfst/src/algorithms/rm_epsilon/rm_epsilon_op.rs, rustfst/src/fst_impls/vector_fst/test.rs, rustfst/src/lib.rs, rustfst/src/semirings/semiring.rs
- Implement one missing operation in Rust : `randgen` (fix https://github.com/Garvys/rustfst/issues/187)
- Add python binding for `randgen`.
- Add __add__, __mul__ and __or__ operator to the VectorFst class.
=> RandGen + (__add__, __mul__ and __or__) added to VectorFst class

rustfst/Cargo.toml
Fix vulnerability issue in `ordered-float` : An issue was discovered in the ordered-float crate before 1.1.1 and 2.x before 2.0.1 for Rust. A NotNan value can contain a NaN.
=> Bump ordered-float to 3.0

rustfst-python/rustfst/fst/const_fst.py, rustfst-python/rustfst/fst/vector_fst.py
`Fst.read` and `Fst.write` now takes `Union[str, Path]` instead of only `Path`.
=> Allow `str` when reading or writing an Fst in Python

rustfst/src/algorithms/randgen/tr_sampler.rs
The seeding was working but en std::HashMap was used making the iteration on it not-deterministic.
As a result, switching to sdt::BTreeMap fixes the issue.
=> Make randgen deterministic when seeded

.github/workflows/native.yml
- Run clippy only on rust version : `1.61.0`
- Add `sleep 30` between `cargo publish`
=> Freeze rust version for clippy to 1.61.0 + sleep between cargo publish

rustfst-python/rustfst/symbol_table.py
Fix : https://github.com/Garvys/rustfst/issues/217
=> SymbolTable.read/write to support both Str and Path in Python

rustfst-python/setup.py
rustfst-python has type declarations (yay!) but mypy does not use them because it has not declared them by including a `py.typed` file in its package (boo!) - see https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages
luckily this is easy to do, just include a `py.typed` file in the package :)
=> Declare presence of types as per PEP561

README.md, rustfst/src/algorithms/all_pairs_shortest_distance.rs, rustfst/src/algorithms/condense.rs, rustfst/src/algorithms/connect.rs, rustfst/src/algorithms/inversion.rs, rustfst/src/algorithms/isomorphic.rs, rustfst/src/algorithms/minimize.rs, rustfst/src/algorithms/mod.rs, rustfst/src/algorithms/optimize.rs, rustfst/src/algorithms/push.rs, rustfst/src/algorithms/relabel_pairs.rs, rustfst/src/algorithms/reverse.rs, rustfst/src/algorithms/reweight.rs, rustfst/src/algorithms/shortest_distance.rs, rustfst/src/algorithms/shortest_path.rs, rustfst/src/algorithms/state_sort.rs, rustfst/src/algorithms/top_sort.rs, rustfst/src/lib.rs
Various documentation improvements
=> Documentation improvements

Cargo.lock, rustfst/Cargo.toml, rustfst/src/algorithms/lazy/cache/simple_hash_map_cache.rs, rustfst/src/algorithms/lazy/state_table.rs, rustfst/src/semirings/log_weight.rs, rustfst/src/semirings/tropical_weight.rs
In particular, this fixes the following warning:
```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v6.1.2
```
=> chore: upgrade nom 6 -> 7

rustfst/src/algorithms/minimize.rs, rustfst/src/algorithms/queue.rs, rustfst/src/algorithms/queues/auto_queue.rs, rustfst/src/algorithms/queues/fifo_queue.rs, rustfst/src/algorithms/queues/lifo_queue.rs, rustfst/src/algorithms/queues/scc_queue.rs, rustfst/src/algorithms/queues/shortest_first_queue.rs, rustfst/src/algorithms/queues/state_order_queue.rs, rustfst/src/algorithms/queues/top_order_queue.rs, rustfst/src/algorithms/queues/trivial_queue.rs, rustfst/src/algorithms/shortest_distance.rs, rustfst/src/algorithms/shortest_path.rs
Presumably the previous pattern was copied straight from the C++ version, which presumably does it that way because of the lack of sum types. But in Rust, it is more idiomatic to return a value, like `Vec::pop`.
=> Make `Queue::dequeue` return the removed value

Cargo.lock, rustfst/src/semirings/integer_weight.rs, rustfst/src/semirings/tropical_weight.rs
Resolving https://github.com/Garvys/rustfst/issues/252 so that FSTs using `IntegerWeight` can be serialized properly.
=> serialize_integer_weight - allow parsing from/to text of IntegerWeight

rustfst-python/rustfst/algorithms/connect.py, rustfst-python/tests/algorithms/test_connect.py
The Python API of the `connect` algorithm was always returning an empty FST. This PR fixes that
=> Fix connect python

.github/workflows/native.yml, Cargo.lock, rustfst-ffi/src/algorithms/compose.rs, rustfst-ffi/src/fst/mod.rs, rustfst-ffi/src/iterators.rs, rustfst-ffi/src/lib.rs, rustfst-ffi/src/string_path.rs, rustfst-ffi/src/string_paths_iterator.rs, rustfst-ffi/src/symbol_table.rs, rustfst-ffi/src/tr.rs, rustfst-ffi/src/trs.rs, rustfst/src/algorithms/connect.rs, rustfst/src/algorithms/minimize.rs, rustfst/src/algorithms/queues/fifo_queue.rs, rustfst/src/algorithms/queues/lifo_queue.rs, rustfst/src/algorithms/queues/trivial_queue.rs, rustfst/src/algorithms/shortest_path.rs, rustfst/src/algorithms/state_sort.rs, rustfst/src/fst_impls/vector_fst/serializable_fst.rs, rustfst/src/fst_traits/paths_iterator.rs, rustfst/src/semirings/boolean_weight.rs, rustfst/src/symbol_table.rs, rustfst/src/tests_openfst/algorithms/compose.rs, rustfst/src/tests_openfst/test_symt.rs, rustfst/src/tests_openfst/test_weights.rs
Clippy has to be run twice to reproduce these results (to cover some
spots that get hit by one lint and then another).
Remaining Clippy issues:
- A lot of instances of `not_unsafe_ptr_arg_deref` under
`rustfst-ffi`. Fixing those would require either skipping the lint at
the top level, which Clippy strongly recommends against, or adding
`unsafe` to many functions, which would be a big change textually and
I think also technically a breaking change.
- Unused tuple members in `CConstFst` and `CConcatFst`. It's not clear
what those are supposed to be doing, but they're `pub`, so I'll just
leave them untouched.
=> Fix up Clippy issues and do some manual cleanups

rustfst-ffi/src/fst/const_fst.rs, rustfst-python/pyproject.toml, rustfst-python/rustfst/fst/const_fst.py, rustfst-python/tests/test_fst.py
Added the `from_vector_fst` method to the python class `ConstFst`, which allows for converting a `VectorFst` to `ConstFst`.
=> Added support for converting VectorFst to ConstFst to ffi/python lib

rustfst-python/mkdocs.yml, rustfst-python/rustfst/algorithms/compose.py, rustfst-python/rustfst/algorithms/connect.py, rustfst-python/rustfst/algorithms/minimize.py, rustfst-python/rustfst/algorithms/optimize.py, rustfst-python/rustfst/algorithms/replace.py, rustfst-python/rustfst/algorithms/reverse.py, rustfst-python/rustfst/algorithms/rm_epsilon.py, rustfst-python/rustfst/algorithms/shortest_path.py, rustfst-python/rustfst/fst/vector_fst.py
The algorithm methods on `VectorFst` were missing documentation, which makes the module considerably less useful.  Here is some documentation (also fixed some of the docstrings in the algorithms modules themselves).
=> fix(docs): Add Python documentation for algorithm methods

rustfst/src/trs.rs
There currently is a bug where all transitions will be iterated instead of only the outgoing transitions of a given state, when iterating over the transitions of `ConstFst` through the FFI. This PR fixes this.
=> Fixed ConstFst FFI Trs iterator

CHANGELOG.md, Cargo.lock, rustfst/src/semirings/mod.rs, rustfst/src/semirings/trivial_weight.rs
This is useful for defining unweighted transducers.
=> Add `TrivialWeight`

CHANGELOG.md, Cargo.lock, rustfst/src/semirings/boolean_weight.rs
According to the definition in [the docs for `WeaklyDivisibleSemiring`](https://docs.rs/rustfst/1.1.2/rustfst/semirings/trait.WeaklyDivisibleSemiring.html), `BooleanWeight` (`S = bool`, `+ = |`, `* = &`, `0 = false`, `1 = true`) should be weakly divisible: there are three combinations `(x, y)` such that `x + y != 0`:
* `x = true`, `y = true`: in this case, we can set `z = true` so that `true = (true | true) & true`.
* `x = true`, `y = false`: we can set `z = true` so that `true = (true | false) & true`.
* `x = false`, `y = true`: we can set `z = false` so that `false = (false | true) & false`.
In fact, `BooleanWeight` is divisible because the inverse of `true` is `true`.
This PR adds an implementation of `WeaklyDivisibleSemiring` for `BooleanWeight`.
=> Implement `WeaklyDivisibleSemiring` for `BooleanWeight`

rustfst-ffi/src/algorithms/inversion.rs, rustfst-ffi/src/algorithms/mod.rs, rustfst-python/docs/rustfst/algorithms/inversion/index.md, rustfst-python/mkdocs.yml, rustfst-python/rustfst/algorithms/inversion.py, rustfst-python/rustfst/algorithms/tr_sort.py, rustfst-python/rustfst/fst/vector_fst.py, rustfst-python/tests/algorithms/test_inversion.py
Fixes: #276 
It was curiously absent, and it is very useful!
Also some minor fixes to documentation (more major ones may come in a separate PR)
=> feat: add `invert` to FFI and Python

rustfst-python/rustfst/algorithms/optimize.py, rustfst-python/rustfst/algorithms/rm_epsilon.py, rustfst-python/rustfst/algorithms/tr_sort.py, rustfst-python/rustfst/algorithms/tr_unique.py, rustfst-python/rustfst/fst/vector_fst.py, rustfst-python/tests/algorithms/test_rm_epsilon.py
Fixes #279 
Also fix the quite bogus code in `rustfst.algorithms.rm_epsilon` which called the underlying function with an extra (bogus) argument and returned a mysterious (bogus) pointer.
=> fix: make Python algorithms consistently return a VectorFst
